# 1. 문제 정의
주어진 제품 및 매장 특성을 기반으로 판매금액(Item_Outlet_Sales) 예측

In [1]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
# train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch4/train.csv")
# test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch4/test.csv")

In [2]:
train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,NCR06,12.500,Low Fat,0.006760,Household,42.8112,OUT013,1987,High,Tier 3,Supermarket Type1,639.1680
1,FDW11,12.600,Low Fat,0.048741,Breads,60.4194,OUT013,1987,High,Tier 3,Supermarket Type1,990.7104
2,FDH32,12.800,Low Fat,0.075997,Fruits and Vegetables,97.1410,OUT013,1987,High,Tier 3,Supermarket Type1,2799.6890
3,FDL52,6.635,Regular,0.046351,Frozen Foods,37.4506,OUT017,2007,NaN,Tier 2,Supermarket Type1,1176.4686
4,FDO09,13.500,Regular,0.125170,Snack Foods,261.4910,OUT013,1987,High,Tier 3,Supermarket Type1,3418.8830
...,...,...,...,...,...,...,...,...,...,...,...,...
6813,NCC54,17.750,Low Fat,0.097863,Health and Hygiene,239.3196,OUT049,1999,Medium,Tier 1,Supermarket Type1,3615.2940
6814,NCF19,13.000,Low Fat,0.035252,Household,48.0034,OUT018,2009,Medium,Tier 3,Supermarket Type2,923.4646
6815,FDU11,4.785,Low Fat,0.092576,Breads,121.0098,OUT035,2004,Small,Tier 2,Supermarket Type1,2530.7058
6816,FDK14,6.980,Low Fat,0.041189,Canned,82.8934,OUT045,2002,NaN,Tier 2,Supermarket Type1,818.9340
6817,NCD31,NaN,Low Fat,0.015360,Household,163.7526,OUT027,1985,Medium,Tier 3,Supermarket Type3,1973.4312

In [3]:
test

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDO38,17.250,Low Fat,0.073251,Canned,76.4986,OUT017,2007,NaN,Tier 2,Supermarket Type1
1,FDO32,6.360,Low Fat,0.120544,Fruits and Vegetables,45.8060,OUT046,1997,Small,Tier 1,Supermarket Type1
2,FDT14,10.695,Regular,0.128247,Dairy,121.8440,OUT018,2009,Medium,Tier 3,Supermarket Type2
3,FDG50,7.405,Low Fat,0.015296,Canned,89.7146,OUT049,1999,Medium,Tier 1,Supermarket Type1
4,FDR11,10.500,Regular,0.142760,Breads,159.3578,OUT049,1999,Medium,Tier 1,Supermarket Type1
...,...,...,...,...,...,...,...,...,...,...,...
1700,NCU18,NaN,Low Fat,0.097769,Household,142.4496,OUT019,1985,Small,Tier 1,Grocery Store
1701,FDY02,NaN,Regular,0.153457,Dairy,264.0910,OUT019,1985,Small,Tier 1,Grocery Store
1702,FDI09,20.750,Regular,0.129864,Seafood,240.1880,OUT018,2009,Medium,Tier 3,Supermarket Type2
1703,DRH23,14.650,Low Fat,0.171282,Hard Drinks,54.0614,OUT017,2007,NaN,Tier 2,Supermarket Type1
1704,NCB18,19.600,Low Fat,0.041291,Household,86.9514,OUT046,1997,Small,Tier 1,Supermarket Type1

# 2. 탐색적 데이터 분석(EDA)

In [4]:
# train.head()
# train.tail()
train.sample(5)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
5682,FDB56,8.750,Regular,0.074743,Fruits and Vegetables,187.6556,OUT049,1999,Medium,Tier 1,Supermarket Type1,5257.1568
483,FDQ11,5.695,Regular,0.067977,Breads,257.4988,OUT018,2009,Medium,Tier 3,Supermarket Type2,3083.9856
3454,FDO40,17.100,Low Fat,0.032761,Frozen Foods,148.8392,OUT018,2009,Medium,Tier 3,Supermarket Type2,2087.9488
4441,DRJ47,18.250,Low Fat,0.044250,Hard Drinks,174.7080,OUT046,1997,Small,Tier 1,Supermarket Type1,2423.5120
1200,FDB26,14.000,Regular,0.031262,Canned,52.5640,OUT035,2004,Small,Tier 2,Supermarket Type1,639.1680

In [5]:
train.shape, test.shape

((6818, 12), (1705, 11))

In [6]:
train.info() 
# 결측치 확인 -> Item_Weight, Outlet_Size

# object 확인 
# Item_Identifier, Item_Fat_Content, Item_Type, 
# Outlet_Identifier, Outlet_Size, Outlet_Location_Type, Outlet_Type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6818 entries, 0 to 6817
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            6818 non-null   object
 1   Item_Weight                5656 non-null   float64
 2   Item_Fat_Content           6818 non-null   object
 3   Item_Visibility            6818 non-null   float64
 4   Item_Type                  6818 non-null   object
 5   Item_MRP                   6818 non-null   float64
 6   Outlet_Identifier          6818 non-null   object
 7   Outlet_Establishment_Year  6818 non-null   int64
 8   Outlet_Size                4878 non-null   object
 9   Outlet_Location_Type       6818 non-null   object
 10  Outlet_Type                6818 non-null   object
 11  Item_Outlet_Sales          6818 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 639.3+ KB

In [7]:
test.info()
# 결측치 확인 -> Item_Weight, Outlet_Size

# object 확인 
# Item_Identifier, Item_Fat_Content, Item_Type, 
# Outlet_Identifier, Outlet_Size, Outlet_Location_Type, Outlet_Type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            1705 non-null   object
 1   Item_Weight                1404 non-null   float64
 2   Item_Fat_Content           1705 non-null   object
 3   Item_Visibility            1705 non-null   float64
 4   Item_Type                  1705 non-null   object
 5   Item_MRP                   1705 non-null   float64
 6   Outlet_Identifier          1705 non-null   object
 7   Outlet_Establishment_Year  1705 non-null   int64
 8   Outlet_Size                1235 non-null   object
 9   Outlet_Location_Type       1705 non-null   object
 10  Outlet_Type                1705 non-null   object
dtypes: float64(3), int64(1), object(7)
memory usage: 146.7+ KB

In [8]:
train.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,5656.000000,6818.000000,6818.000000,6818.000000,6818.000000
mean,12.872703,0.066121,140.419533,1997.885890,2190.941459
std,4.651034,0.051383,62.067861,8.339795,1706.131256
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.785000,0.026914,93.610050,1987.000000,836.577700
50%,12.600000,0.053799,142.448300,1999.000000,1806.648300
75%,17.000000,0.095273,185.060150,2004.000000,3115.944000
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [9]:
test.describe()

       Item_Weight  Item_Visibility     Item_MRP  Outlet_Establishment_Year
count  1404.000000      1705.000000  1705.000000                1705.000000
mean     12.796984         0.066174   143.285107                1997.615836
std       4.613957         0.052465    63.063146                   8.497423
min       4.555000         0.000000    31.955800                1985.000000
25%       8.710000         0.027571    94.743600                1987.000000
50%      12.600000         0.054234   144.512800                1999.000000
75%      16.700000         0.092927   187.755600                2004.000000
max      21.350000         0.311090   266.888400                2009.000000

In [10]:
train.describe(include="O")

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type
count,6818,6818,6818,6818,4878,6818,6818
unique,1554,5,16,10,3,3,4
top,FDW26,Low Fat,Snack Foods,OUT046,Medium,Tier 3,Supermarket Type1
freq,9,4092,963,763,2228,2664,4474

In [11]:
train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1162
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1940
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [12]:
train.isnull().sum().sum()

3102

In [13]:
test.describe(include="O")

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type
count,1705,1705,1705,1705,1235,1705,1705
unique,1077,5,16,10,3,3,4
top,FDG33,Low Fat,Fruits and Vegetables,OUT013,Medium,Tier 3,Supermarket Type1
freq,4,997,272,207,565,686,1103

In [14]:
test.isnull().sum()

Item_Identifier                0
Item_Weight                  301
Item_Fat_Content               0
Item_Visibility                0
Item_Type                      0
Item_MRP                       0
Outlet_Identifier              0
Outlet_Establishment_Year      0
Outlet_Size                  470
Outlet_Location_Type           0
Outlet_Type                    0
dtype: int64

In [15]:
test.isnull().sum().sum()

771

# 3. 데이터 전처리

In [16]:
# 결측값 채우기(무게 : 최소값, 사이즈 : 최빈값)
train['Item_Weight'] = train['Item_Weight'].fillna(train['Item_Weight'].min()) # min : 4.555 로 채워짐
# train.describe() # 결측치 없음을 확인

# train.describe(include="O")
train['Outlet_Size'] = train['Outlet_Size'].fillna(train['Outlet_Size'].mode()[0])
# train.info() # 확인용

test['Item_Weight'] = test['Item_Weight'].fillna(test['Item_Weight'].min())
test['Outlet_Size'] = test['Outlet_Size'].fillna(test['Outlet_Size'].mode()[0])
# test.info() # 확인용

In [17]:
train.describe() # 이상치 생략

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,6818.000000,6818.000000,6818.000000,6818.000000,6818.000000
mean,11.455107,0.066121,140.419533,1997.885890,2190.941459
std,5.265718,0.051383,62.067861,8.339795,1706.131256
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,6.690000,0.026914,93.610050,1987.000000,836.577700
50%,11.000000,0.053799,142.448300,1999.000000,1806.648300
75%,16.100000,0.095273,185.060150,2004.000000,3115.944000
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [18]:
# 컬럼제거
train.drop('Item_Identifier', axis=1, inplace=True)
train.drop('Outlet_Identifier', axis=1, inplace=True)

test.drop('Item_Identifier', axis=1, inplace=True)
test.drop('Outlet_Identifier', axis=1, inplace=True)
train.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,12.500,Low Fat,0.006760,Household,42.8112,1987,High,Tier 3,Supermarket Type1,639.1680
1,12.600,Low Fat,0.048741,Breads,60.4194,1987,High,Tier 3,Supermarket Type1,990.7104
2,12.800,Low Fat,0.075997,Fruits and Vegetables,97.1410,1987,High,Tier 3,Supermarket Type1,2799.6890
3,6.635,Regular,0.046351,Frozen Foods,37.4506,2007,Medium,Tier 2,Supermarket Type1,1176.4686
4,13.500,Regular,0.125170,Snack Foods,261.4910,1987,High,Tier 3,Supermarket Type1,3418.8830

# OLS

In [19]:
# OLS - 선형회귀에서만 사용할것(분류는 X)

from statsmodels.formula.api import ols

# y항목컬럼명 저장
y_col = "Item_Outlet_Sales"

# y를 뺀 x값 후보들(수치형, 범주형 다 포함됨)
X_cols = [c for c in train.columns if c != y_col]
print(X_cols)
print()

# formula 생성
formula = f"{y_col} ~ " + " + ".join(X_cols)
print(formula)
print()

# OLS 모델 적용
model = ols(formula, data=train).fit()
print(model)
print()

# 확인
print(model.summary())

['Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_Type', 'Item_MRP', 'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

Item_Outlet_Sales ~ Item_Weight + Item_Fat_Content + Item_Visibility + Item_Type + Item_MRP + Outlet_Establishment_Year + Outlet_Size + Outlet_Location_Type + Outlet_Type

<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x70330f430410>

                            OLS Regression Results
==============================================================================
Dep. Variable:      Item_Outlet_Sales   R-squared:                       0.566
Model:                            OLS   Adj. R-squared:                  0.564
Method:                 Least Squares   F-statistic:                     295.1
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        02:13:18   Log-Likelihood:                -57567.
No. Observations:                6818   AIC:                         1.152e+05
Df Residuals:                    6787   BIC:                         1.154e+05
Df Model:                          30
Covariance Type:            nonrobust
======================================================================================================
                                         coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                          -8.124e+04   2.24e+04     -3.635      0.000   -1.25e+05   -3.74e+04
Item_Fat_Content[T.Low Fat]            0.7708     72.685      0.011      0.992    -141.715     143.257
Item_Fat_Content[T.Regular]           58.8473     75.669      0.778      0.437     -89.488     207.183
Item_Fat_Content[T.low fat]           68.4691    140.068      0.489      0.625    -206.108     343.046
Item_Fat_Content[T.reg]              -83.1595    135.834     -0.612      0.540    -349.437     183.118
Item_Type[T.Breads]                  -43.7344     95.579     -0.458      0.647    -231.099     143.630
Item_Type[T.Breakfast]                 7.7343    127.614      0.061      0.952    -242.429     257.898
Item_Type[T.Canned]                  -11.4371     69.973     -0.163      0.870    -148.606     125.731
Item_Type[T.Dairy]                   -94.2435     68.859     -1.369      0.171    -229.228      40.741
Item_Type[T.Frozen Foods]            -56.6160     65.193     -0.868      0.385    -184.415      71.183
Item_Type[T.Fruits and Vegetables]    -4.1182     61.435     -0.067      0.947    -124.549     116.313
Item_Type[T.Hard Drinks]             -68.9815    100.557     -0.686      0.493    -266.104     128.141
Item_Type[T.Health and Hygiene]      -79.7769     75.688     -1.054      0.292    -228.150      68.596
Item_Type[T.Household]               -58.5434     66.623     -0.879      0.380    -189.146      72.059
Item_Type[T.Meat]                    -50.3029     78.053     -0.644      0.519    -203.312     102.706
Item_Type[T.Others]                  -74.1123    109.346     -0.678      0.498    -288.465     140.240
Item_Type[T.Seafood]                  67.0517    166.876      0.402      0.688    -260.078     394.181
Item_Type[T.Snack Foods]             -63.8606     61.469     -1.039      0.299    -184.359      56.638
Item_Type[T.Soft Drinks]             -82.9761     78.862     -1.052      0.293    -237.571      71.618
Item_Type[T.Starchy Foods]           -76.3410    116.262     -0.657      0.511    -304.251     151.569
Outlet_Size[T.Medium]               -886.9780    284.022     -3.123      0.002   -1443.751    -330.205
Outlet_Size[T.Small]                -808.3725    277.071     -2.918      0.004   -1351.518    -265.227
Outlet_Location_Type[T.Tier 2]      -226.5131     79.863     -2.836      0.005    -383.070     -69.956
Outlet_Location_Type[T.Tier 3]      -471.3878    162.295     -2.905      0.004    -789.537    -153.239
Outlet_Type[T.Supermarket Type1]    1460.9907    158.790      9.201      0.000    1149.712    1772.270
Outlet_Type[T.Supermarket Type2]    1171.4715    142.872      8.199      0.000     891.397    1451.546
Outlet_Type[T.Supermarket Type3]    3916.1248    164.958     23.740      0.000    3592.756    4239.494
Item_Weight                            1.4338      3.246      0.442      0.659      -4.929       7.797
Item_Visibility                     -301.4072    278.181     -1.083      0.279    -846.728     243.914
Item_MRP                              15.6224      0.221     70.602      0.000      15.189      16.056
Outlet_Establishment_Year             40.4321     11.388      3.550      0.000      18.109      62.756
==============================================================================
Omnibus:                      786.042   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1938.233
Skew:                           0.669   Prob(JB):                         0.00
Kurtosis:                       5.243   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

## 1) OLS p-value 높은 값 제거

In [20]:
# OLS - pvalue값 높은값만 제거 

# p-value 0.05 이상인 컬럼 제거해보기 -> 확인해보면 Item_Fat_Content, Item_Type -> 삭제 처리
model.pvalues[model.pvalues > 0.05]

# list 로 묶어서 반복문으로 컬럼을 제거 or 단순 삭제
# list = model.pvalues[model.pvalues > 0.05].index.tolist()

train = train.drop('Item_Fat_Content', axis=1)
train = train.drop('Item_Type', axis=1)

test = test.drop('Item_Fat_Content', axis=1)
test = test.drop('Item_Type', axis=1)

In [21]:
from statsmodels.formula.api import ols

# y항목컬럼명 저장
y_col = "Item_Outlet_Sales"

# y를 뺀 x값 후보들(수치형, 범주형 다 포함됨)
X_cols = [c for c in train.columns if c != y_col]
print(X_cols)
print()

# formula 생성
formula = f"{y_col} ~ " + " + ".join(X_cols)
print(formula)
print()

# OLS 모델 적용
model = ols(formula, data=train).fit()
print(model)
print()

# 확인
print(model.summary())

['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

Item_Outlet_Sales ~ Item_Weight + Item_Visibility + Item_MRP + Outlet_Establishment_Year + Outlet_Size + Outlet_Location_Type + Outlet_Type

<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x7032ee81c050>

                            OLS Regression Results
==============================================================================
Dep. Variable:      Item_Outlet_Sales   R-squared:                       0.565
Model:                            OLS   Adj. R-squared:                  0.565
Method:                 Least Squares   F-statistic:                     804.5
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        02:13:18   Log-Likelihood:                -57573.
No. Observations:                6818   AIC:                         1.152e+05
Df Residuals:                    6806   BIC:                         1.153e+05
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
Intercept                        -8.079e+04   2.23e+04     -3.619      0.000   -1.25e+05    -3.7e+04
Outlet_Size[T.Medium]             -878.9886    283.595     -3.099      0.002   -1434.923    -323.054
Outlet_Size[T.Small]              -799.6318    276.648     -2.890      0.004   -1341.949    -257.314
Outlet_Location_Type[T.Tier 2]    -223.9019     79.734     -2.808      0.005    -380.205     -67.599
Outlet_Location_Type[T.Tier 3]    -465.1553    162.001     -2.871      0.004    -782.727    -147.583
Outlet_Type[T.Supermarket Type1]  1468.7205    158.519      9.265      0.000    1157.974    1779.467
Outlet_Type[T.Supermarket Type2]  1175.3242    142.695      8.237      0.000     895.597    1455.052
Outlet_Type[T.Supermarket Type3]  3915.6567    164.703     23.774      0.000    3592.787    4238.526
Item_Weight                          1.2264      3.221      0.381      0.703      -5.088       7.541
Item_Visibility                   -249.0102    276.578     -0.900      0.368    -791.189     293.169
Item_MRP                            15.6090      0.220     71.026      0.000      15.178      16.040
Outlet_Establishment_Year           40.1856     11.373      3.533      0.000      17.891      62.480
==============================================================================
Omnibus:                      782.121   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1920.684
Skew:                           0.668   Prob(JB):                         0.00
Kurtosis:                       5.231   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

## 2) OLS 다중공선성 높은 변수 제거

In [22]:
# OLS 다중공선성 의심(다중공선성 : 설명변수들(독립변수) 사이에 서로 강한 상관관계 존재)
# Cond. No. -> 높을수록 X

# 발생 원인
# 범주형 독립변수 간의 중복된 의미가 있을 때 -> 범주형-수치형 검정(카이제곱)
# 연속된 수치값(ex 날짜정보)이 포함되어 있을 때 -> 컬럼 삭제
# 수치형 독립변수들간의 변수 범위 차이가 클 때 -> 스케일링

#  Cond. No.
# < 30 : 문제 없음
# 30 ~ 100 : 약한 다중공선성 가능성
# 100 ~ 1,000 : 다중공선성 의심
# >1,000 : 심각한 다중공선성 가능성 있음
# > 10^5(100000) : 수치적으로 매우 불안정 - 경고 수준

# 다중공선성 원인 변수찾기(VIF) - 다중공선성의 정도를 수치로 측정한 지표
from statsmodels.stats.outliers_influence import variance_inflation_factor

X_cols = [c for c in train.columns if c != y_col] # 위에서 컬럼 삭제를 했기 때문에 다시 X_cols 가져오기
print(X_cols)
X = train[X_cols].select_dtypes(include=['float', 'int'])
print(X) # Item_Weight  Item_Visibility  Item_MRP  Outlet_Establishment_Year

vif = pd.DataFrame()
vif['Feature'] = X.columns
print(X.shape)
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif

# VIf > 10 -> 다중공선성 심함
# VIF > 5 -> 주의 필요

# 해결책
# 수치형 변수 스케일링 - StandardScaler 또는 MinMaxScaler
# 다중공선성 높은 변수 제거 - VIF 10이상인 변수 제거
# Ridge/Lasso 회귀로 대체 - 정규화로 공선성 완화

['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']
      Item_Weight  Item_Visibility  Item_MRP  Outlet_Establishment_Year
0          12.500         0.006760   42.8112                       1987
1          12.600         0.048741   60.4194                       1987
2          12.800         0.075997   97.1410                       1987
3           6.635         0.046351   37.4506                       2007
4          13.500         0.125170  261.4910                       1987
...           ...              ...       ...                        ...
6813       17.750         0.097863  239.3196                       1999
6814       13.000         0.035252   48.0034                       2009
6815        4.785         0.092576  121.0098                       2004
6816        6.980         0.041189   82.8934                       2002
6817        4.555         0.015360  163.7526                       1985

[6818 rows x 4 columns]
(6818, 4)

                     Feature        VIF
0                Item_Weight   5.802119
1            Item_Visibility   2.665509
2                   Item_MRP   6.121111
3  Outlet_Establishment_Year  12.748339

In [23]:
# 다중공선성 10이상인 컬럼 삭제
train = train.drop('Outlet_Establishment_Year', axis=1)
test = test.drop('Outlet_Establishment_Year', axis=1)

# OLS 확인
from statsmodels.stats.outliers_influence import variance_inflation_factor

X_cols = [c for c in train.columns if c != y_col] # 위에서 컬럼 삭제를 했기 때문에 다시 X_cols 가져오기
print(X_cols)
X = train[X_cols].select_dtypes(include=['float', 'int'])
print(X) # Item_Weight  Item_Visibility  Item_MRP  Outlet_Establishment_Year

vif = pd.DataFrame()
vif['Feature'] = X.columns
print(X.shape)
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif

['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']
      Item_Weight  Item_Visibility  Item_MRP
0          12.500         0.006760   42.8112
1          12.600         0.048741   60.4194
2          12.800         0.075997   97.1410
3           6.635         0.046351   37.4506
4          13.500         0.125170  261.4910
...           ...              ...       ...
6813       17.750         0.097863  239.3196
6814       13.000         0.035252   48.0034
6815        4.785         0.092576  121.0098
6816        6.980         0.041189   82.8934
6817        4.555         0.015360  163.7526

[6818 rows x 3 columns]
(6818, 3)

           Feature       VIF
0      Item_Weight  3.532542
1  Item_Visibility  2.241316
2         Item_MRP  3.756969

In [24]:
from statsmodels.formula.api import ols

# y항목컬럼명 저장
y_col = "Item_Outlet_Sales"

# y를 뺀 x값 후보들(수치형, 범주형 다 포함됨)
X_cols = [c for c in train.columns if c != y_col]
print(X_cols)
print()

# formula 생성
formula = f"{y_col} ~ " + " + ".join(X_cols)
print(formula)
print()

# OLS 모델 적용
model = ols(formula, data=train).fit()
print(model)
print()

# 확인
print(model.summary())

['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

Item_Outlet_Sales ~ Item_Weight + Item_Visibility + Item_MRP + Outlet_Size + Outlet_Location_Type + Outlet_Type

<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x7032ee7ed110>

                            OLS Regression Results
==============================================================================
Dep. Variable:      Item_Outlet_Sales   R-squared:                       0.564
Model:                            OLS   Adj. R-squared:                  0.564
Method:                 Least Squares   F-statistic:                     882.2
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        02:13:19   Log-Likelihood:                -57580.
No. Observations:                6818   AIC:                         1.152e+05
Df Residuals:                    6807   BIC:                         1.153e+05
Df Model:                          10
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
Intercept                        -1917.6231    152.278    -12.593      0.000   -2216.136   -1619.110
Outlet_Size[T.Medium]               61.5101     97.958      0.628      0.530    -130.519     253.539
Outlet_Size[T.Small]                94.7821    111.723      0.848      0.396    -124.230     313.794
Outlet_Location_Type[T.Tier 2]      23.5906     38.131      0.619      0.536     -51.158      98.339
Outlet_Location_Type[T.Tier 3]      10.5645     90.177      0.117      0.907    -166.210     187.339
Outlet_Type[T.Supermarket Type1]  1967.5442     72.164     27.265      0.000    1826.080    2109.008
Outlet_Type[T.Supermarket Type2]  1617.7371     68.506     23.614      0.000    1483.443    1752.031
Outlet_Type[T.Supermarket Type3]  3394.2922     73.245     46.341      0.000    3250.708    3537.876
Item_Weight                          1.3062      3.224      0.405      0.685      -5.013       7.626
Item_Visibility                   -239.8330    276.799     -0.866      0.386    -782.445     302.779
Item_MRP                            15.6036      0.220     70.943      0.000      15.172      16.035
==============================================================================
Omnibus:                      779.202   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1916.165
Skew:                           0.665   Prob(JB):                         0.00
Kurtosis:                       5.231   Cond. No.                     3.17e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.17e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## 3) OLS 수치형 변수 스케일링

In [25]:
from sklearn.preprocessing import StandardScaler

# 1. 수치형 컬럼 자동 선택
num_cols = train.select_dtypes(exclude=['object']).columns
# 2. 스케일러 선언
scaler = StandardScaler()
# 3. 수치형 컬럼만 스케일링
train[num_cols] = scaler.fit_transform(train[num_cols])
# 4. 결과확인
print('스케일링 완료된 수치형 컬럼들 : ')
print(num_cols.tolist())
print(train.head())

스케일링 완료된 수치형 컬럼들 :
['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Item_Outlet_Sales']
   Item_Weight  Item_Visibility  Item_MRP Outlet_Size Outlet_Location_Type  \
0     0.198448        -1.155377 -1.572722        High               Tier 3
1     0.217440        -0.338271 -1.289008        High               Tier 3
2     0.255424         0.192206 -0.697329        High               Tier 3
3    -0.915442        -0.384799 -1.659095      Medium               Tier 2
4     0.388369         1.149287  1.950774        High               Tier 3

         Outlet_Type  Item_Outlet_Sales
0  Supermarket Type1          -0.909594
1  Supermarket Type1          -0.703533
2  Supermarket Type1           0.356826
3  Supermarket Type1          -0.594648
4  Supermarket Type1           0.719776

In [26]:
from statsmodels.formula.api import ols

# y항목컬럼명 저장
y_col = "Item_Outlet_Sales"

# y를 뺀 x값 후보들(수치형, 범주형 다 포함됨)
X_cols = [c for c in train.columns if c != y_col]
print(X_cols)
print()

# formula 생성
formula = f"{y_col} ~ " + " + ".join(X_cols)
print(formula)
print()

# OLS 모델 적용
model = ols(formula, data=train).fit()
print(model)
print()

# 확인
print(model.summary())

['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

Item_Outlet_Sales ~ Item_Weight + Item_Visibility + Item_MRP + Outlet_Size + Outlet_Location_Type + Outlet_Type

<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x7032ebf6f390>

                            OLS Regression Results
==============================================================================
Dep. Variable:      Item_Outlet_Sales   R-squared:                       0.564
Model:                            OLS   Adj. R-squared:                  0.564
Method:                 Least Squares   F-statistic:                     882.2
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        02:13:19   Log-Likelihood:                -6840.8
No. Observations:                6818   AIC:                         1.370e+04
Df Residuals:                    6807   BIC:                         1.378e+04
Df Model:                          10
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
Intercept                           -1.1245      0.090    -12.466      0.000      -1.301      -0.948
Outlet_Size[T.Medium]                0.0361      0.057      0.628      0.530      -0.077       0.149
Outlet_Size[T.Small]                 0.0556      0.065      0.848      0.396      -0.073       0.184
Outlet_Location_Type[T.Tier 2]       0.0138      0.022      0.619      0.536      -0.030       0.058
Outlet_Location_Type[T.Tier 3]       0.0062      0.053      0.117      0.907      -0.097       0.110
Outlet_Type[T.Supermarket Type1]     1.1533      0.042     27.265      0.000       1.070       1.236
Outlet_Type[T.Supermarket Type2]     0.9483      0.040     23.614      0.000       0.870       1.027
Outlet_Type[T.Supermarket Type3]     1.9896      0.043     46.341      0.000       1.905       2.074
Item_Weight                          0.0040      0.010      0.405      0.685      -0.015       0.024
Item_Visibility                     -0.0072      0.008     -0.866      0.386      -0.024       0.009
Item_MRP                             0.5676      0.008     70.943      0.000       0.552       0.583
==============================================================================
Omnibus:                      779.202   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1916.165
Skew:                           0.665   Prob(JB):                         0.00
Kurtosis:                       5.231   Cond. No.                         25.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [27]:
# 레이블 인코딩(범주형 -> 수치형으로)
from sklearn.preprocessing import LabelEncoder
cols = train.columns[train.dtypes == object]
for col in cols:
    le = LabelEncoder()
    le.fit(pd.concat([train[col], test[col]], axis=0)) # 행합치기
    train[col] = le.transform(train[col]) 
    test[col] = le.transform(test[col])

In [28]:
train # 확인작업

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,0.198448,-1.155377,-1.572722,0,2,1,-0.909594
1,0.217440,-0.338271,-1.289008,0,2,1,-0.703533
2,0.255424,0.192206,-0.697329,0,2,1,0.356826
3,-0.915442,-0.384799,-1.659095,1,1,1,-0.594648
4,0.388369,1.149287,1.950774,0,2,1,0.719776
...,...,...,...,...,...,...,...
6813,1.195536,0.617792,1.593535,1,0,1,0.834905
6814,0.293408,-0.600825,-1.489062,1,2,2,-0.742950
6815,-1.266797,0.514896,-0.312741,2,1,1,0.199158
6816,-0.849919,-0.485264,-0.926894,1,1,1,-0.804222
6817,-1.310479,-0.987989,0.375956,1,2,3,-0.127497

In [29]:
test # 확인작업

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,17.250,0.073251,76.4986,1,1,1
1,6.360,0.120544,45.8060,2,0,1
2,10.695,0.128247,121.8440,1,2,2
3,7.405,0.015296,89.7146,1,0,1
4,10.500,0.142760,159.3578,1,0,1
...,...,...,...,...,...,...
1700,4.555,0.097769,142.4496,2,0,0
1701,4.555,0.153457,264.0910,2,0,0
1702,20.750,0.129864,240.1880,1,2,2
1703,14.650,0.171282,54.0614,1,1,1
1704,19.600,0.041291,86.9514,2,0,1

# 4. 검증데이터 분할

In [30]:
# y값 분할
target = train.pop('Item_Outlet_Sales')
target

0      -0.909594
1      -0.703533
2       0.356826
3      -0.594648
4       0.719776
          ...
6813    0.834905
6814   -0.742950
6815    0.199158
6816   -0.804222
6817   -0.127497
Name: Item_Outlet_Sales, Length: 6818, dtype: float64

In [31]:
# train : val = 8 : 2 = 학습용 : 검증용

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=0)
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((5454, 6), (1364, 6), (5454,), (1364,))

# 5. 머신러닝 학습 및 평가

In [32]:
# 평가지표 확인
from sklearn.metrics import mean_squared_error # MSE(평균제곱오차)
from sklearn.metrics import mean_absolute_error # MAE(평균절대오차)
from sklearn.metrics import root_mean_squared_error # RMSE(제곱평균오차)
from sklearn.metrics import r2_score # R2score(결정계수)

# LIGHTGBM 학습
import lightgbm as lgb
model = lgb.LGBMRegressor(random_state=0, verbose=-1)
model.fit(X_train, y_train)
y_pred_2 = model.predict(X_val)

lgm_mse = mean_squared_error(y_val, y_pred_2)
lgm_mae = mean_absolute_error(y_val, y_pred_2)
lgm_rmse = root_mean_squared_error(y_val, y_pred_2)
lgm_r2 = r2_score(y_val, y_pred_2)

print("MSE : ", lgm_mse) # 오차를 제곱해 평균을 낸 값 - 값 클수록 예측이 실제와 다름
print("MAE : ", lgm_mae) # 오차를 절대값으로 계산 - 값 클수록 예측이 실제와 다름
print("RMSE : ", lgm_rmse) 
print("R²score : ", lgm_r2)

MSE :  0.3760642689289045
MAE :  0.4283359341117688
RMSE :  0.6132407919642205
R²score :  0.5783903199230017

In [33]:
# 1. LIGHTGBM 학습
# MSE :  1114002.6635464637
# MAE :  735.6497591742841
# RMSE :  1055.463245947704
# R²score :  0.5708851384345557

# 2. p-value > 0.05 컬럼 제거 후
# MSE :  1092404.771446767
# MAE :  731.6743299323026
# RMSE :  1045.181693030818
# R²score :  0.5792046665485746

# 3. 다중공선성이 높은 변수들 제거 후
# MSE :  1105424.9719734981
# MAE :  731.8602125397052
# RMSE :  1051.3919212042188
# R²score :  0.5741892732022107

# 4. 수치형변수 스케일링 후 
# MSE :  0.3760642689289045
# MAE :  0.4283359341117688
# RMSE :  0.6132407919642205
# R²score :  0.5783903199230017

# 상관계수

In [34]:
# 임계값 조절
TARGET_CORR_TH = 0.03 # 상관계수 임계값

# 숫자형 기준으로 상관계수 계산
df_corr = train.copy()
df_corr['__target__'] = y_train # y값 같은 데이터프레임에 보이도록 넣어주기
print(df_corr)

corr_with_target = df_corr.corr(numeric_only=True)['__target__'].drop('__target__') # 기준 값 y값.자기자신은 제외 -> 나머지 X와 Y의 관계만 확인
print(corr_with_target)

      Item_Weight  Item_Visibility  Item_MRP  Outlet_Size  \
0        0.198448        -1.155377 -1.572722            0
1        0.217440        -0.338271 -1.289008            0
2        0.255424         0.192206 -0.697329            0
3       -0.915442        -0.384799 -1.659095            1
4        0.388369         1.149287  1.950774            0
...           ...              ...       ...          ...
6813     1.195536         0.617792  1.593535            1
6814     0.293408        -0.600825 -1.489062            1
6815    -1.266797         0.514896 -0.312741            2
6816    -0.849919        -0.485264 -0.926894            1
6817    -1.310479        -0.987989  0.375956            1

      Outlet_Location_Type  Outlet_Type  __target__
0                        2            1   -0.909594
1                        2            1         NaN
2                        2            1    0.356826
3                        1            1   -0.594648
4                        2            1    0.719776
...                    ...          ...         ...
6813                     0            1         NaN
6814                     2            2         NaN
6815                     1            1    0.199158
6816                     1            1         NaN
6817                     2            3   -0.127497

[6818 rows x 7 columns]
Item_Weight            -0.048096
Item_Visibility        -0.131916
Item_MRP                0.568184
Outlet_Size            -0.071065
Outlet_Location_Type    0.080007
Outlet_Type             0.403363
Name: __target__, dtype: float64

In [35]:
# 유지할 컬럼(= 타깃과의 절대 상관이 임계값 이상인 컬럼만 추출)
keep_features = corr_with_target[corr_with_target.abs() >= TARGET_CORR_TH].index.tolist()
print(keep_features)
print()

# 제거할 컬럼 - y값에 영향을 끼치지 않는 변수
problem_features = corr_with_target[corr_with_target.abs() < TARGET_CORR_TH].index.tolist()
print(problem_features)

['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

[]

In [36]:
# -----------------------------
# 컬럼제거
# -----------------------------
train.drop('Item_Fat_Content', axis=1, inplace=True)
train.drop('Item_Type', axis=1, inplace=True)

test.drop('Item_Fat_Content', axis=1, inplace=True)
test.drop('Item_Type', axis=1, inplace=True)

# 확인
train.shape, test.shape

KeyError: "['Item_Fat_Content'] not found in axis"

In [ ]:
from sklearn.model_selection import train_test_split

X_train_re, X_val_re, y_train_re, y_val_re = train_test_split(train, target, test_size=0.2, random_state=0)
X_train_re.shape, X_val_re.shape, y_train_re.shape, y_val_re.shape

In [ ]:
import lightgbm as lgb
model = lgb.LGBMRegressor(random_state=0, verbose=-1)
model.fit(X_train_re, y_train_re)
y_pred_re = model.predict(X_val_re)
y_pred_re

In [ ]:
lgm_mse_re = mean_squared_error(y_val_re, y_pred_re)
lgm_mae_re = mean_absolute_error(y_val_re, y_pred_re)
lgm_rmse_re = root_mean_squared_error(y_val_re, y_pred_re)
lgm_r2_re = r2_score(y_val_re, y_pred_re)

print("MSE : ", lgm_mse_re) # 오차를 제곱해 평균을 낸 값 - 값 클수록 예측이 실제와 다름
print("MAE : ", lgm_mae_re) # 오차를 절대값으로 계산 - 값 클수록 예측이 실제와 다름
print("RMSE : ", lgm_rmse_re) 
print("R2score : ", lgm_r2_re)