In [1]:
# 문제정의(KAGGLE : https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/overview)

# ---------------------------
## 1. 해결과제
# ---------------------------
# - 주어진 주택 데이터(물리적 특성 + 주변 환경)를 이용해 **최종 판매 가격(SalePrice)** 예측
# - 단순 선형 회귀가 아니라 다양한 회귀 기법을 적용해 성능 최적화가 목표

# ---------------------------
# 2. 타겟 변수
# ---------------------------
# - **SalePrice**  
# - 주택의 실제 판매 가격 (회귀 문제의 종속 변수)

# ---------------------------
# 3 데이터셋 컬럼 정리
# ---------------------------
# ## 1). ID / Target
# - **Id**: 샘플 고유 번호
# - **SalePrice**: 주택 판매 가격 (타겟 변수, train에만 존재)

# ---

# ## 2). 주택 일반 정보
# - **MSSubClass**: 건물 클래스 (주택 유형 코드)
# - **MSZoning**: 구역 분류 (주거, 상업 등)
# - **Street**: 도로 종류 (포장/비포장)
# - **Alley**: 골목 접근 유형
# - **LotFrontage**: 도로와 접한 면적 길이 (ft)
# - **LotArea**: 대지 면적 (sq ft)
# - **LotShape**: 대지 형태 (정방형/불규칙 등)
# - **LandContour**: 지형 윤곽 (평지, 경사 등)
# - **Utilities**: 사용 가능한 설비 (전기, 수도 등)
# - **LotConfig**: 대지 구성 (독립, 구석, 4면도로 등)
# - **LandSlope**: 대지 경사 정도
# - **Neighborhood**: 주택이 위치한 동네
# - **Condition1**: 주요 도로/철도 근접 조건
# - **Condition2**: 보조 도로/철도 근접 조건
# - **BldgType**: 건물 유형 (단독, 연립, 아파트 등)
# - **HouseStyle**: 주택 스타일 (1층, 2층, 다층 등)

# ---

# ## 3). 건축 관련
# - **OverallQual**: 전반적 자재와 마감 품질 (1~10)
# - **OverallCond**: 전반적 주택 상태 (1~10)
# - **YearBuilt**: 건축 연도
# - **YearRemodAdd**: 리모델링 연도
# - **RoofStyle**: 지붕 형태
# - **RoofMatl**: 지붕 자재
# - **Exterior1st**: 외장재 1
# - **Exterior2nd**: 외장재 2
# - **MasVnrType**: 벽돌 베니어 유형
# - **MasVnrArea**: 벽돌 베니어 면적 (sq ft)
# - **ExterQual**: 외장재 품질
# - **ExterCond**: 외장재 상태

# ---

# ## 4). 기초/지하
# - **Foundation**: 기초 유형
# - **BsmtQual**: 지하 높이
# - **BsmtCond**: 지하 상태
# - **BsmtExposure**: 지하 채광 정도
# - **BsmtFinType1**: 지하 마감 유형 1
# - **BsmtFinSF1**: 지하 마감 면적 1 (sq ft)
# - **BsmtFinType2**: 지하 마감 유형 2
# - **BsmtFinSF2**: 지하 마감 면적 2 (sq ft)
# - **BsmtUnfSF**: 지하 미마감 면적 (sq ft)
# - **TotalBsmtSF**: 지하 전체 면적 (sq ft)

# ---

# ## 5). 생활 공간
# - **Heating**: 난방 종류
# - **HeatingQC**: 난방 품질
# - **CentralAir**: 중앙 에어컨 유무
# - **Electrical**: 전기 시스템
# - **1stFlrSF**: 1층 면적 (sq ft)
# - **2ndFlrSF**: 2층 면적 (sq ft)
# - **LowQualFinSF**: 낮은 품질 마감 면적 (sq ft)
# - **GrLivArea**: 지상 생활 면적 (sq ft)

# ---

# ## 6). 방 관련
# - **BsmtFullBath**: 지하 전체 욕실 개수
# - **BsmtHalfBath**: 지하 반 욕실 개수
# - **FullBath**: 전체 욕실 개수
# - **HalfBath**: 반 욕실 개수
# - **BedroomAbvGr**: 지상 침실 개수
# - **KitchenAbvGr**: 지상 주방 개수
# - **KitchenQual**: 주방 품질
# - **TotRmsAbvGrd**: 지상 전체 방 개수
# - **Functional**: 주택 기능 상태 (정상/이상 등)

# ---

# ## 7). 기타 공간
# - **Fireplaces**: 벽난로 개수
# - **FireplaceQu**: 벽난로 품질
# - **GarageType**: 차고 유형
# - **GarageYrBlt**: 차고 건축 연도
# - **GarageFinish**: 차고 내부 마감
# - **GarageCars**: 차고 차량 수용 가능 대수
# - **GarageArea**: 차고 면적 (sq ft)
# - **GarageQual**: 차고 품질
# - **GarageCond**: 차고 상태
# - **PavedDrive**: 포장 진입로 여부

# ---

# ## 8). 외부/부속 공간
# - **WoodDeckSF**: 목재 데크 면적 (sq ft)
# - **OpenPorchSF**: 오픈 현관 면적 (sq ft)
# - **EnclosedPorch**: 밀폐 현관 면적 (sq ft)
# - **3SsnPorch**: 3계절용 현관 면적 (sq ft)
# - **ScreenPorch**: 스크린 현관 면적 (sq ft)
# - **PoolArea**: 수영장 면적 (sq ft)
# - **PoolQC**: 수영장 품질
# - **Fence**: 울타리 품질
# - **MiscFeature**: 기타 특이 시설
# - **MiscVal**: 기타 시설 가치

# ---

# ## 9). 판매 정보
# - **MoSold**: 판매 월
# - **YrSold**: 판매 연도
# - **SaleType**: 판매 유형
# - **SaleCondition**: 판매 조건

In [2]:
# ---------------------------------
# 라이브러리 가져오기
# ---------------------------------
import pandas as pd

train = pd.read_csv("./train.csv")
test = pd.read_csv("./test.csv")

In [3]:
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [5]:
# ---------------------------------
# EDA
# ---------------------------------

In [6]:
train.shape, test.shape

((1460, 81), (1459, 80))

In [7]:
train.info()
# 결측치 확인
# LotFrontage, Alley, MasVnrType, MasVnrArea, BsmtQual, BsmtCond, BsmtExposure, 
# BsmtFinType1, BsmtFinType2, Electrical, FireplaceQu, GarageType, GarageYrBlt,
# GarageFinish, GarageQual, GarageCond, PoolQC, Fence, MiscFeature

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [8]:
print(train.isnull().sum().to_string())

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0

In [9]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     565 non-null    object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [10]:
print(test.isnull().sum().to_string())

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       227
LotArea             0
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType        894
MasVnrArea         15
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           44
BsmtCond           45
BsmtExposure       44
BsmtFinType1       42
BsmtFinSF1          1
BsmtFinType2       42
BsmtFinSF2          1
BsmtUnfSF           1
TotalBsmtSF         1
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        2
BsmtHalfBath        2
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         1
TotRmsAbvGrd        0
Functional          2
Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond         78
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1456
Fence            1169
MiscFeature      1408
MiscVal             0
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0

In [11]:
train.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [12]:
list(set(train.dtypes.tolist())) # train 전체의 dtype 확인가능

[dtype('int64'), dtype('O'), dtype('float64')]

In [13]:
train.describe(include="O")

# object만 뽑아내기
# train.select_dtypes(include = 'object') 
# int, float 찾고 싶을 때 ['int64', 'float'] 입력

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1460,1460,91,1460,1460,1460,1460,1460,1460,1460,...,1379,1379,1379,1379,1460,7,281,54,1460,1460
unique,5,2,2,4,4,2,5,3,25,9,...,6,3,5,5,3,3,4,4,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,Gd,MnPrv,Shed,WD,Normal
freq,1151,1454,50,925,1311,1459,1052,1382,225,1260,...,870,605,1311,1326,1340,3,157,49,1267,1198

In [14]:
test.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1459.000000,1459.000000,1232.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1444.000000,1458.000000,...,1458.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,2190.000000,57.378341,68.580357,9819.161069,6.078821,5.553804,1971.357779,1983.662783,100.709141,439.203704,...,472.768861,93.174777,48.313914,24.243317,1.794380,17.064428,1.744345,58.167923,6.104181,2007.769705
std,421.321334,42.746880,22.376841,4955.517327,1.436812,1.113740,30.390071,21.130467,177.625900,455.268042,...,217.048611,127.744882,68.883364,67.227765,20.207842,56.609763,30.491646,630.806978,2.722432,1.301740
min,1461.000000,20.000000,21.000000,1470.000000,1.000000,1.000000,1879.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,1825.500000,20.000000,58.000000,7391.000000,5.000000,5.000000,1953.000000,1963.000000,0.000000,0.000000,...,318.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000
50%,2190.000000,50.000000,67.000000,9399.000000,6.000000,5.000000,1973.000000,1992.000000,0.000000,350.500000,...,480.000000,0.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,2554.500000,70.000000,80.000000,11517.500000,7.000000,6.000000,2001.000000,2004.000000,164.000000,753.500000,...,576.000000,168.000000,72.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,2919.000000,190.000000,200.000000,56600.000000,10.000000,9.000000,2010.000000,2010.000000,1290.000000,4010.000000,...,1488.000000,1424.000000,742.000000,1012.000000,360.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000

In [15]:
test.describe(include="O")

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1455,1459,107,1459,1459,1457,1459,1459,1459,1459,...,1383,1381,1381,1381,1459,3,290,51,1458,1459
unique,5,2,2,4,4,1,5,3,25,9,...,6,3,4,5,3,2,4,3,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
freq,1114,1453,70,934,1311,1457,1081,1396,218,1251,...,853,625,1293,1328,1301,2,172,46,1258,1204

In [16]:
# ---------------------------------
# 데이터 전처리
# ---------------------------------

# y값 분할
target = train.pop('SalePrice')
target

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [17]:
# 후보 데이터만 사용
features = [
    "OverallQual",   # 전반적 자재/마감 품질
    "GrLivArea",     # 지상 생활 면적
    "GarageCars",    # 차고 수용 차량 수
    "GarageArea",    # 차고 면적
    "TotalBsmtSF",   # 지하 전체 면적
    "1stFlrSF",      # 1층 면적
    "FullBath",      # 전체 욕실 개수
    "YearBuilt",     # 건축 연도
    "YearRemodAdd",  # 리모델링 연도
    "KitchenQual",   # 주방 품질 (범주형)
    "Fireplaces",    # 벽난로 개수
    "Neighborhood"   # 위치 (범주형)
]
train = train[features]
test = test[features]

In [18]:
train.info() # 확인 - 결측치 X

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OverallQual   1460 non-null   int64
 1   GrLivArea     1460 non-null   int64
 2   GarageCars    1460 non-null   int64
 3   GarageArea    1460 non-null   int64
 4   TotalBsmtSF   1460 non-null   int64
 5   1stFlrSF      1460 non-null   int64
 6   FullBath      1460 non-null   int64
 7   YearBuilt     1460 non-null   int64
 8   YearRemodAdd  1460 non-null   int64
 9   KitchenQual   1460 non-null   object
 10  Fireplaces    1460 non-null   int64
 11  Neighborhood  1460 non-null   object
dtypes: int64(10), object(2)
memory usage: 137.0+ KB

In [19]:
test.info() # 확인 - 결측치 O

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OverallQual   1459 non-null   int64
 1   GrLivArea     1459 non-null   int64
 2   GarageCars    1458 non-null   float64
 3   GarageArea    1458 non-null   float64
 4   TotalBsmtSF   1458 non-null   float64
 5   1stFlrSF      1459 non-null   int64
 6   FullBath      1459 non-null   int64
 7   YearBuilt     1459 non-null   int64
 8   YearRemodAdd  1459 non-null   int64
 9   KitchenQual   1458 non-null   object
 10  Fireplaces    1459 non-null   int64
 11  Neighborhood  1459 non-null   object
dtypes: float64(3), int64(7), object(2)
memory usage: 136.9+ KB

In [20]:
test.describe() # GarageCars, GarageArea -> 결측치를 min으로

,OverallQual,GrLivArea,GarageCars,GarageArea,TotalBsmtSF,1stFlrSF,FullBath,YearBuilt,YearRemodAdd,Fireplaces
count,1459.000000,1459.000000,1458.000000,1458.000000,1458.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.00000
mean,6.078821,1486.045922,1.766118,472.768861,1046.117970,1156.534613,1.570939,1971.357779,1983.662783,0.58122
std,1.436812,485.566099,0.775945,217.048611,442.898624,398.165820,0.555190,30.390071,21.130467,0.64742
min,1.000000,407.000000,0.000000,0.000000,0.000000,407.000000,0.000000,1879.000000,1950.000000,0.00000
25%,5.000000,1117.500000,1.000000,318.000000,784.000000,873.500000,1.000000,1953.000000,1963.000000,0.00000
50%,6.000000,1432.000000,2.000000,480.000000,988.000000,1079.000000,2.000000,1973.000000,1992.000000,0.00000
75%,7.000000,1721.000000,2.000000,576.000000,1305.000000,1382.500000,2.000000,2001.000000,2004.000000,1.00000
max,10.000000,5095.000000,5.000000,1488.000000,5095.000000,5095.000000,4.000000,2010.000000,2010.000000,4.00000

In [21]:
# 수치형 컬럼(X)의 결측치 채우기(최소/최대/평균/중앙값 중 최소값 선택)
test['GarageCars'] = test['GarageCars'].fillna(test['GarageCars'].min())
test['GarageArea'] = test['GarageArea'].fillna(test['GarageArea'].min())
test['TotalBsmtSF'] = test['TotalBsmtSF'].fillna(test['TotalBsmtSF'].min())

/tmp/ipykernel_19641/4253531353.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['GarageCars'] = test['GarageCars'].fillna(test['GarageCars'].min())
/tmp/ipykernel_19641/4253531353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['GarageArea'] = test['GarageArea'].fillna(test['GarageArea'].min())
/tmp/ipykernel_19641/4253531353.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['TotalBsmtSF'] = test['TotalBsmtSF'].fillna(test['TotalBsmtSF'].min())

In [22]:
test.describe(include="O")

       KitchenQual Neighborhood
count         1458         1459
unique           4           25
top             TA        NAmes
freq           757          218

In [23]:
# 범주형 컬럼(X) 결측치 채우기(최빈값/사분위수 범위내 중 최소값/최대값...)
# KitchenQual : Ex=우수, Gd=좋음, TA=보통, Fa=나쁨
test['KitchenQual'] = test['KitchenQual'].fillna(test['KitchenQual'].mode()[0])
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OverallQual   1459 non-null   int64
 1   GrLivArea     1459 non-null   int64
 2   GarageCars    1459 non-null   float64
 3   GarageArea    1459 non-null   float64
 4   TotalBsmtSF   1459 non-null   float64
 5   1stFlrSF      1459 non-null   int64
 6   FullBath      1459 non-null   int64
 7   YearBuilt     1459 non-null   int64
 8   YearRemodAdd  1459 non-null   int64
 9   KitchenQual   1459 non-null   object
 10  Fireplaces    1459 non-null   int64
 11  Neighborhood  1459 non-null   object
dtypes: float64(3), int64(7), object(2)
memory usage: 136.9+ KB

/tmp/ipykernel_19641/2016617586.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['KitchenQual'] = test['KitchenQual'].fillna(test['KitchenQual'].mode()[0])

In [24]:
# 이상치 - 생략

In [25]:
# 인코딩(LIGHTGBM 사용시 범주형(object) -> 카테고리(category) 자료형
train['KitchenQual'] = train['KitchenQual'].astype('category')
train['Neighborhood'] = train['Neighborhood'].astype('category')
# train.info()

test['KitchenQual'] = test['KitchenQual'].astype('category')
test['Neighborhood'] = test['Neighborhood'].astype('category')
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OverallQual   1459 non-null   int64
 1   GrLivArea     1459 non-null   int64
 2   GarageCars    1459 non-null   float64
 3   GarageArea    1459 non-null   float64
 4   TotalBsmtSF   1459 non-null   float64
 5   1stFlrSF      1459 non-null   int64
 6   FullBath      1459 non-null   int64
 7   YearBuilt     1459 non-null   int64
 8   YearRemodAdd  1459 non-null   int64
 9   KitchenQual   1459 non-null   category
 10  Fireplaces    1459 non-null   int64
 11  Neighborhood  1459 non-null   category
dtypes: category(2), float64(3), int64(7)
memory usage: 117.9 KB

/tmp/ipykernel_19641/803850698.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['KitchenQual'] = train['KitchenQual'].astype('category')
/tmp/ipykernel_19641/803850698.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Neighborhood'] = train['Neighborhood'].astype('category')
/tmp/ipykernel_19641/803850698.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['KitchenQual'] = test['KitchenQual'].astype('category')
/tmp/ipykernel_19641/803850698.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Neighborhood'] = test['Neighborhood'].astype('category')

In [26]:
# ---------------------------------
# 검증 데이터 분할 train - val (8,2)
# ---------------------------------
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=0)
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((1168, 12), (292, 12), (1168,), (292,))

In [27]:
# ---------------------------------
# 학습 및 평가(MSE, MAE , R2..)
# ---------------------------------
import lightgbm as lgb
model = lgb.LGBMRegressor(random_state=0, verbose=-1)
model.fit(X_train, y_train) # 학습
y_pred = model.predict(X_val) # 예측
y_pred

array([341764.75749812, 141688.47910067, 120677.81758381, 228575.75211451,
        92251.28852243, 113043.99740768, 225809.54820198, 127978.36444965,
       563876.8571553 , 146429.51181508, 200409.89106504, 173586.80944635,
       220551.87875481, 117533.88502192, 128088.77204484, 132381.60556189,
       207334.32809832, 117411.78140702, 144575.01788236, 172587.93147109,
       128809.21044769, 143704.1417425 , 109073.95609355, 175374.0920053 ,
       188612.94734439, 190423.50138547, 176349.39322053,  71867.25871788,
       306058.79134878, 123242.47692563, 118737.94715063, 181409.04171498,
       140585.05457823, 288160.12655409, 404077.30328448, 176080.76221067,
       267782.91798305, 130654.79465395, 250707.29123974, 299490.56030609,
       202327.97574432, 130428.26202987, 189989.11439171, 302960.56851511,
       388234.26728087, 141637.48155231, 122178.45559983, 123184.20341559,
       154213.64188508,  97465.09571438, 401084.00749283, 141343.96728508,
       178784.83192722,  82926.61052917, 222801.09508002, 112117.53874166,
       123032.98219899, 238327.65667361, 136467.54212947,  94943.04010812,
       137396.0536451 , 132412.0406357 , 155256.48496603, 147540.15891439,
       196250.48380827, 174327.50442926, 126216.67945328, 227813.18380025,
       154377.03720648, 183231.34504434, 168425.92417838, 117276.77820865,
        72799.07260249, 216339.17102588, 107721.42677542, 265235.17730468,
       122679.86675641, 104446.26692093, 287895.66886757, 157684.77258613,
       131483.65299747, 132419.20220589, 109364.94730069, 143852.85483236,
       313432.00030292, 204226.67673723,  99803.69618924, 198462.25675858,
       163440.08453014, 140525.88579455, 189136.08871499, 172844.6438425 ,
       182576.08371476, 213124.70300005, 188610.03305767, 146791.08442704,
       211575.29867252, 131194.12942064, 113056.51781512, 157924.3694924 ,
       237276.81664013, 195829.89761302, 115461.77984164, 141861.24023135,
        91994.12571909, 279734.48582073, 152697.94971682,  97970.73426055,
       176838.26324824, 107559.59526147, 130357.87330551, 115839.24044974,
       185955.8001408 , 114413.27770448, 168291.23420815, 159806.39562318,
       465525.44492075, 132825.61039229, 202893.37234211, 268919.79733758,
       146120.23186766, 174973.05024484, 128306.09149316, 199124.1440094 ,
       217892.14450831, 232727.09743079, 414404.79391208, 203983.31831108,
       202790.34195207, 168808.55462597, 186519.41835816, 194496.65640885,
       143854.75843138, 181931.5787949 , 111661.78734344, 226073.58688013,
       127119.05464064, 194917.27272655, 116086.87627367, 176795.84405548,
       167653.91049514, 139460.97299237, 310252.75746183, 158075.10588519,
       136209.68107728, 182818.08459775, 230641.75835352, 139499.18862816,
       300716.01278706, 224518.85756523, 164804.38160351, 359886.47976333,
       280940.45665271, 151276.10674901, 184756.52948921, 313694.16156253,
       117338.74242296, 206925.69175793, 114481.92464306, 166426.40860047,
       114193.28483634, 139124.52927028, 187323.25339178, 118063.59573965,
       239648.3576451 , 112312.47432575, 150757.94638843, 297384.75840901,
       193789.77256691, 180043.21570052, 156846.32261927, 154420.18106777,
       187742.12970843, 168074.7409868 , 123262.54373414, 106553.42517856,
       138253.1257135 , 254001.6841644 , 105431.87191318, 152049.01894788,
       279220.78585374, 214898.92934457, 101427.53602165, 328196.33290662,
        93833.04849467, 171823.23741002,  90933.66210655, 194051.00934242,
       192418.17823729, 143704.1417425 , 143362.25151951, 148192.45264923,
       226957.62261981, 137749.75924759, 117833.82126639, 142712.80809233,
        86235.88875088, 133025.93132685, 163463.2375475 , 127759.49364092,
       135352.93533524, 199521.34183889, 114513.32720257, 123991.14347299,
       148718.04328744, 166575.36584473, 161796.64622987, 316733.39680353,
       268058.66030976,  73162.10876472, 153219.36302706, 277136.28203188,
        91085.53293941,  91106.93297294, 280372.14921181, 196956.54457763,
       188729.44285294, 280153.92334104, 272220.95517617,  72945.24756347,
       203152.27735626, 170695.46054784, 127821.5625222 , 122249.71197412,
       192618.21657195, 239426.71389071, 255733.05588623, 194225.10050575,
       143463.99718739, 164222.68801916,  90431.69350942, 155741.52428078,
        99461.85692093, 151271.78088997, 200851.97720453, 135622.45625252,
       135321.70603039, 122416.72638644,  96450.79376885, 179621.31239198,
       109789.64329478, 183383.68831867, 194291.53192182, 218556.10670993,
       153988.45782694, 200287.32538616, 209483.15304266, 173327.25410039,
       136987.69256179, 198458.15869864, 185043.43905077, 267863.76282327,
        93184.54751561, 422200.59195184, 234776.08665907, 231296.11185564,
        97879.98055799, 205281.20537489, 433562.3107188 , 423464.71499523,
       203307.3629002 , 126997.59193908, 125498.54537944,  79562.48607056,
       429307.89014584, 355782.91668714, 351769.31175287,  72194.1472878 ,
       207010.62899162, 295594.53953031, 136829.39565888, 286682.6021735 ,
       132735.25495888, 198004.21798449, 106739.01284959, 219974.95953946,
       193873.97070918, 181696.28386531, 234943.87755607, 103806.83658049,
       130078.48843374, 385251.86508593, 161907.32607424, 129778.77565173,
       198906.25068692, 130903.17208488, 118242.92827595, 273447.16769597,
       482040.79760923, 151298.82694817,  67250.26191674,  88551.31745634])

In [28]:
# 평가지표 확인
from sklearn.metrics import mean_squared_error # MSE(평균제곱오차)
from sklearn.metrics import mean_absolute_error # MAE(평균절대오차)
from sklearn.metrics import root_mean_squared_error # RMSE(제곱평균오차)
from sklearn.metrics import r2_score # R2score(결정계수)

lgm_mse = mean_squared_error(y_val, y_pred)
lgm_mae = mean_absolute_error(y_val, y_pred)
lgm_rmse = root_mean_squared_error(y_val, y_pred)
lgm_r2 = r2_score(y_val, y_pred)

print("MSE : ", lgm_mse) # 오차를 제곱해 평균을 낸 값 - 값 클수록 예측이 실제와 다름
print("MAE : ", lgm_mae) # 오차를 절대값으로 계산 - 값 클수록 예측이 실제와 다름
print("RMSE : ", lgm_rmse)
print("R2score : ", lgm_r2)

MSE :  1138255660.1912904
MAE :  19091.970142754628
RMSE :  33738.044700179205
R2score :  0.8351751535112408

In [29]:
# 결과 평가
# MSE :  1138255660.1912904 -> 다른 모델과 비교시 사용(튜닝 이전/이후 비교) 낮은 값 코드 사용
# MAE :  19091.970142754628 -> 예측값과 실제 집값의 차이가 평균적으로 19000 다ㅏㄹ러
# RMSE :  33738.044700179205 -> 예측값과 실제 집값의 차이가 33000 - 약 20% 정도 오차
# R2score :  0.8351751535112408 -> 모델이 집값에 대한 예측을 83.5% 정도 설명이 가능(우수한 성능)

In [ ]:
# 파일로 저장
pred = model.predict(test)
submit = pd.DataFrame({'pred' : pred})
submit.to_csv('result.csv', index=False)

In [33]:
# SAMPLE X 전달 -> 집값 예측 확인

sample = {
    "OverallQual" : 5,   # 전반적 자재/마감 품질(1-10)
    "GrLivArea" : 1800,     # 지상 생활 면적
    "GarageCars" : 2,    # 차고 수용 차량 수
    "GarageArea" : 500,    # 차고 면적
    "TotalBsmtSF" : 800,   # 지하 전체 면적
    "1stFlrSF" : 1200,      # 1층 면적
    "FullBath" : 2,      # 전체 욕실 개수
    "YearBuilt" : 2005,     # 건축 연도
    "YearRemodAdd" : 2010,  # 리모델링 연도
    "KitchenQual" : 'TA',   # 주방 품질 (범주형)
    "Fireplaces": 1,    # 벽난로 개수
    "Neighborhood" : "CollgCr"   # 위치 (범주형)
}
sample_df = pd.DataFrame([sample])
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OverallQual   1 non-null      int64
 1   GrLivArea     1 non-null      int64
 2   GarageCars    1 non-null      int64
 3   GarageArea    1 non-null      int64
 4   TotalBsmtSF   1 non-null      int64
 5   1stFlrSF      1 non-null      int64
 6   FullBath      1 non-null      int64
 7   YearBuilt     1 non-null      int64
 8   YearRemodAdd  1 non-null      int64
 9   KitchenQual   1 non-null      object
 10  Fireplaces    1 non-null      int64
 11  Neighborhood  1 non-null      object
dtypes: int64(10), object(2)
memory usage: 228.0+ bytes

In [34]:
sample_df['KitchenQual'] = sample_df['KitchenQual'].astype('category')
sample_df['Neighborhood'] = sample_df['Neighborhood'].astype('category')

In [35]:
pred_price = model.predict(sample_df)
print("예측 집값 : ", pred_price)

예측 집값 :  [187981.40745232]