# 문제 정의
## 여러 개의 신용 등급 클래스 중 하나로 분류하는 모델을 개발

- 고객별 신용등급 분류  
1 - BAD, 2 - STANDARD, 3 - GOOD  
타깃(라벨, y값) : Credit_Score

# 라이브러리 가져오기

In [1]:
import pandas as pd

# 데이터 불러오기
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')

In [2]:
train

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Score,Credit_Mix,...,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
0,56.0,16.0,11.0,35.598217,120.0,Yes,229.093478,252.385965,1,Bad,...,15.0,36597.56,8.0,10.0,29.0,5.0,3143.796667,22.49,2963.18,122.900223
1,49.0,23.0,12.0,25.553106,120.0,Yes,104.613906,219.105944,1,Bad,...,28.0,32057.30,9.0,8.0,16.0,7.0,2606.441667,1.40,1327.26,164.859426
2,34.0,20.0,6.0,40.039954,174.0,Yes,338.626965,251.265589,1,Bad,...,46.0,75868.80,6.0,10.0,32.0,7.0,6074.400000,3.60,1432.71,297.547446
3,21.0,13.0,8.0,25.711678,143.0,NM,116.816864,259.927960,2,Standard,...,46.0,17092.69,7.0,3.0,19.0,7.0,1695.390833,16.40,1417.06,62.794260
4,19.0,13.0,6.0,39.140463,138.0,Yes,87.262887,626.212330,1,Bad,...,45.0,81471.96,6.0,6.0,25.0,5.0,6763.330000,27.09,2679.69,202.857783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,13.0,20.0,1.0,28.311154,358.0,No,160.363681,317.931124,2,Standard,...,25.0,36661.93,6.0,3.0,10.0,4.0,2915.160833,1.16,314.26,73.221279
9996,32.0,13.0,5.0,39.741948,299.0,Yes,278.359264,160.416098,2,Standard,...,48.0,28161.85,8.0,5.0,6.0,4.0,2422.820833,7.72,699.69,93.506721
9997,13.0,9.0,8.0,25.111049,203.0,Yes,39.334921,352.515899,2,Standard,...,36.0,39912.86,3.0,4.0,17.0,6.0,3498.071667,15.72,1734.43,197.956347
9998,10.0,13.0,6.0,32.237478,309.0,Yes,115.463482,354.829742,2,Standard,...,45.0,26918.38,6.0,5.0,10.0,2.0,2442.198333,5.48,1054.90,43.926610
9999,14.0,12.0,2.0,32.525388,288.0,NM,655.490743,636.379413,3,Good,...,50.0,148786.04,4.0,4.0,4.0,3.0,12492.836667,6.71,399.45,237.413511

In [3]:
test

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Mix,Payment_Behaviour,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
0,4.0,8.0,2.0,33.444469,239.0,No,104.467859,503.976904,Good,Low_spent_Small_value_payments,54.0,43754.320,5.0,7.0,7.0,1.0,3938.193333,7.55,515.73,35.374569
1,31.0,19.0,14.0,27.762143,93.0,Yes,149.137974,219.372773,Bad,High_spent_Small_value_payments,40.0,18836.230,6.0,8.0,16.0,6.0,1280.685833,14.26,1310.56,49.557837
2,55.0,16.0,17.0,38.985106,179.0,Yes,21.862086,299.525207,Standard,Low_spent_Small_value_payments,27.0,9360.515,8.0,6.0,15.0,5.0,531.042917,11.92,2113.29,21.716999
3,47.0,20.0,8.0,25.577407,93.0,Yes,170.009215,161.283266,Bad,Low_spent_Small_value_payments,34.0,30386.200,7.0,8.0,21.0,9.0,2650.183333,17.53,4902.83,193.725852
4,26.0,11.0,7.0,36.580166,207.0,Yes,296.552469,177.231449,Standard,High_spent_Medium_value_payments,36.0,49187.070,6.0,6.0,25.0,6.0,3823.922500,12.04,1357.26,198.608332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,27.0,12.0,4.0,38.977305,383.0,Yes,39.695906,472.869011,Standard,High_spent_Medium_value_payments,32.0,38839.220,8.0,4.0,19.0,3.0,3272.601667,1.83,1203.51,64.695250
9996,22.0,19.0,2.0,25.582411,363.0,Yes,89.540202,360.819998,Standard,High_spent_Medium_value_payments,51.0,24251.490,8.0,4.0,14.0,1.0,1991.957500,10.53,1062.17,18.835550
9997,20.0,15.0,11.0,26.764418,233.0,Yes,53.574209,311.419464,Bad,Low_spent_Small_value_payments,45.0,15806.840,6.0,5.0,21.0,3.0,1140.236667,3.41,2580.63,29.029993
9998,60.0,19.0,8.0,35.262194,99.0,NM,46.902804,389.691164,Bad,High_spent_Small_value_payments,40.0,35462.520,8.0,9.0,31.0,4.0,2718.210000,13.14,2371.87,75.227032
9999,56.0,20.0,7.0,28.104679,139.0,Yes,31.318074,284.545251,Bad,Low_spent_Small_value_payments,26.0,10222.150,6.0,5.0,18.0,9.0,899.845833,27.34,4473.83,54.121258

# EDA

In [4]:
train.shape, test.shape

((10000, 21), (10000, 20))

In [5]:
train[['Credit_Score']].value_counts()

Credit_Score
2               5237
1               2978
3               1785
Name: count, dtype: int64

In [6]:
train.info() # 결측치 없음 확인, Dtype 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       10000 non-null  float64
 1   Num_of_Delayed_Payment    10000 non-null  float64
 2   Num_Credit_Inquiries      10000 non-null  float64
 3   Credit_Utilization_Ratio  10000 non-null  float64
 4   Credit_History_Age        10000 non-null  float64
 5   Payment_of_Min_Amount     10000 non-null  object
 6   Amount_invested_monthly   10000 non-null  float64
 7   Monthly_Balance           10000 non-null  float64
 8   Credit_Score              10000 non-null  int64
 9   Credit_Mix                10000 non-null  object
 10  Payment_Behaviour         10000 non-null  object
 11  Age                       10000 non-null  float64
 12  Annual_Income             10000 non-null  float64
 13  Num_Bank_Accounts         10000 non-null  float64
 14  Num_Credit_Card           10000 non-null  float64
 15  Interest_Rate             10000 non-null  float64
 16  Num_of_Loan               10000 non-null  float64
 17  Monthly_Inhand_Salary     10000 non-null  float64
 18  Changed_Credit_Limit      10000 non-null  float64
 19  Outstanding_Debt          10000 non-null  float64
 20  Total_EMI_per_month       10000 non-null  float64
dtypes: float64(17), int64(1), object(3)
memory usage: 1.6+ MB

In [7]:
train.describe()

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Amount_invested_monthly,Monthly_Balance,Credit_Score,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
count,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,21.263100,13.381300,5.79400,32.306216,220.501400,195.497580,400.130732,1.880700,33.33680,50318.451889,5.382900,5.538000,14.468200,3.525700,4182.906254,10.435633,1428.996096,105.114322
std,14.778976,6.217876,3.86772,5.093599,99.204263,196.150962,211.034108,0.679789,10.73122,38171.440801,2.566271,2.096186,8.687977,2.441585,3175.891720,6.501954,1158.852422,125.502925
min,0.000000,0.000000,0.00000,20.719745,2.000000,0.000000,0.007760,1.000000,14.00000,7006.035000,0.000000,0.000000,1.000000,0.000000,303.645417,0.500000,0.230000,0.000000
25%,10.000000,9.000000,3.00000,28.075839,144.000000,74.056997,268.741936,1.000000,24.00000,19259.307500,4.000000,4.000000,7.000000,2.000000,1626.342083,5.507500,562.340000,28.588769
50%,18.000000,14.000000,6.00000,32.310153,219.000000,130.089440,334.854343,2.000000,33.00000,36875.140000,5.000000,5.000000,13.000000,3.000000,3073.272917,9.410000,1168.235000,65.971478
75%,28.000000,18.000000,8.00000,36.491502,301.000000,234.960725,470.351899,2.000000,42.00000,71507.587500,7.000000,7.000000,20.000000,5.000000,5936.870000,14.630000,1960.420000,144.429302
max,67.000000,28.000000,17.00000,47.103409,404.000000,1674.337665,1567.208309,3.000000,56.00000,179987.280000,10.000000,11.000000,34.000000,9.000000,15167.180000,29.980000,4998.070000,1701.955013

In [8]:
train.describe(include="O") # 범주형

       Payment_of_Min_Amount Credit_Mix               Payment_Behaviour
count                  10000      10000                           10000
unique                     3          3                               6
top                      Yes   Standard  Low_spent_Small_value_payments
freq                    5269       4591                            3416

In [9]:
train.isnull().sum() # 결측값 없음(info에서 확인했지만 다시 한 번 확인)

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Score                0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

In [10]:
train.isnull().sum().sum()

0

In [11]:
test.info() # 결측치, Dtype 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       10000 non-null  float64
 1   Num_of_Delayed_Payment    10000 non-null  float64
 2   Num_Credit_Inquiries      10000 non-null  float64
 3   Credit_Utilization_Ratio  10000 non-null  float64
 4   Credit_History_Age        10000 non-null  float64
 5   Payment_of_Min_Amount     10000 non-null  object
 6   Amount_invested_monthly   10000 non-null  float64
 7   Monthly_Balance           10000 non-null  float64
 8   Credit_Mix                10000 non-null  object
 9   Payment_Behaviour         10000 non-null  object
 10  Age                       10000 non-null  float64
 11  Annual_Income             10000 non-null  float64
 12  Num_Bank_Accounts         10000 non-null  float64
 13  Num_Credit_Card           10000 non-null  float64
 14  Interest_Rate             10000 non-null  float64
 15  Num_of_Loan               10000 non-null  float64
 16  Monthly_Inhand_Salary     10000 non-null  float64
 17  Changed_Credit_Limit      10000 non-null  float64
 18  Outstanding_Debt          10000 non-null  float64
 19  Total_EMI_per_month       10000 non-null  float64
dtypes: float64(17), object(3)
memory usage: 1.5+ MB

In [12]:
test.describe() # 수치형

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Amount_invested_monthly,Monthly_Balance,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,21.097900,13.255200,5.752500,32.186729,221.825800,193.117531,400.580605,33.482000,50108.745203,5.340400,5.528100,14.472300,3.544600,4166.494700,10.416235,1416.394165,103.957612
std,14.797811,6.251238,3.865998,5.159005,99.213024,195.419810,212.389930,10.739097,38406.986599,2.586039,2.090609,8.773878,2.426891,3194.843717,6.521728,1148.313667,121.991063
min,0.000000,0.000000,0.000000,20.172942,2.000000,0.000000,1.222495,14.000000,7006.035000,0.000000,0.000000,1.000000,0.000000,303.645417,0.500000,0.340000,0.000000
25%,10.000000,9.000000,3.000000,27.894659,145.000000,72.723155,270.578579,25.000000,19214.681250,3.000000,4.000000,7.000000,2.000000,1616.490417,5.407500,560.410000,29.240525
50%,18.000000,14.000000,5.000000,32.166358,220.000000,128.333887,336.320248,33.000000,36475.525000,5.000000,5.000000,13.000000,3.000000,3052.810833,9.340000,1159.810000,65.377135
75%,28.000000,18.000000,8.000000,36.504712,304.000000,234.830616,465.525296,42.000000,71025.400000,7.000000,7.000000,20.000000,5.000000,5913.288333,14.832500,1941.615000,142.311157
max,67.000000,28.000000,29.000000,50.000000,404.000000,1804.355694,1533.102266,56.000000,179987.280000,10.000000,11.000000,34.000000,9.000000,15204.633333,29.970000,4997.050000,1701.955013

In [13]:
test.describe(include="O") # 범주형

       Payment_of_Min_Amount Credit_Mix               Payment_Behaviour
count                  10000      10000                           10000
unique                     3          3                               6
top                      Yes   Standard  Low_spent_Small_value_payments
freq                    5167       4590                            3498

In [14]:
test.isnull().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

In [15]:
test.isnull().sum().sum()

0

# 전처리

In [2]:
# 변수 y 분리
y_train = train.pop("Credit_Score")

In [21]:
y_train.value_counts

Credit_Score
2    5237
1    2978
3    1785
Name: count, dtype: int64

In [16]:
# 기존 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

cols = train.columns[train.dtypes == object]
cols 
# Index(['Payment_of_Min_Amount', 'Credit_Mix', 'Payment_Behaviour'], dtype='object')

Index(['Payment_of_Min_Amount', 'Credit_Mix', 'Payment_Behaviour'], dtype='object')

In [17]:
for col in cols:
    le = LabelEncoder() # 각 열마다 독립적인 인코딩 규칙을 적용
    le.fit(pd.concat([train[col], test[col]], axis=0)) # 행합치기
    train[col] = le.transform(train[col]) # fit_transform() : 학습 및 변환
    test[col] = le.transform(test[col])

In [7]:
# 레이블 인코딩 대체방법
# 범주형 type -> category로 변경

# train.info() # object 확인 :  Payment_of_Min_Amount, Credit_Mix, Payment_Behaviour

train['Payment_of_Min_Amount'] = train['Payment_of_Min_Amount'].astype('category')
train['Credit_Mix'] = train['Credit_Mix'].astype('category')
train['Payment_Behaviour'] = train['Payment_Behaviour'].astype('category')

test['Payment_of_Min_Amount'] = test['Payment_of_Min_Amount'].astype('category')
test['Credit_Mix'] = test['Credit_Mix'].astype('category')
test['Payment_Behaviour'] = test['Payment_Behaviour'].astype('category')

train.info()
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       10000 non-null  float64
 1   Num_of_Delayed_Payment    10000 non-null  float64
 2   Num_Credit_Inquiries      10000 non-null  float64
 3   Credit_Utilization_Ratio  10000 non-null  float64
 4   Credit_History_Age        10000 non-null  float64
 5   Payment_of_Min_Amount     10000 non-null  category
 6   Amount_invested_monthly   10000 non-null  float64
 7   Monthly_Balance           10000 non-null  float64
 8   Credit_Mix                10000 non-null  category
 9   Payment_Behaviour         10000 non-null  category
 10  Age                       10000 non-null  float64
 11  Annual_Income             10000 non-null  float64
 12  Num_Bank_Accounts         10000 non-null  float64
 13  Num_Credit_Card           10000 non-null  float64
 14  Interest_Rate             10000 non-null  float64
 15  Num_of_Loan               10000 non-null  float64
 16  Monthly_Inhand_Salary     10000 non-null  float64
 17  Changed_Credit_Limit      10000 non-null  float64
 18  Outstanding_Debt          10000 non-null  float64
 19  Total_EMI_per_month       10000 non-null  float64
dtypes: category(3), float64(17)
memory usage: 1.3 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       10000 non-null  float64
 1   Num_of_Delayed_Payment    10000 non-null  float64
 2   Num_Credit_Inquiries      10000 non-null  float64
 3   Credit_Utilization_Ratio  10000 non-null  float64
 4   Credit_History_Age        10000 non-null  float64
 5   Payment_of_Min_Amount     10000 non-null  category
 6   Amount_invested_monthly   10000 non-null  float64
 7   Monthly_Balance           10000 non-null  float64
 8   Credit_Mix                10000 non-null  category
 9   Payment_Behaviour         10000 non-null  category
 10  Age                       10000 non-null  float64
 11  Annual_Income             10000 non-null  float64
 12  Num_Bank_Accounts         10000 non-null  float64
 13  Num_Credit_Card           10000 non-null  float64
 14  Interest_Rate             10000 non-null  float64
 15  Num_of_Loan               10000 non-null  float64
 16  Monthly_Inhand_Salary     10000 non-null  float64
 17  Changed_Credit_Limit      10000 non-null  float64
 18  Outstanding_Debt          10000 non-null  float64
 19  Total_EMI_per_month       10000 non-null  float64
dtypes: category(3), float64(17)
memory usage: 1.3 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       10000 non-null  float64
 1   Num_of_Delayed_Payment    10000 non-null  float64
 2   Num_Credit_Inquiries      10000 non-null  float64
 3   Credit_Utilization_Ratio  10000 non-null  float64
 4   Credit_History_Age        10000 non-null  float64
 5   Payment_of_Min_Amount     10000 non-null  category
 6   Amount_invested_monthly   10000 non-null  float64
 7   Monthly_Balance           10000 non-null  float64
 8   Credit_Mix                10000 non-null  category
 9   Payment_Behaviour         10000 non-null  category
 10  Age                       10000 non-null  float64
 11  Annual_Income             10000 non-null  float64
 12  Num_Bank_Accounts         10000 non-null  float64
 13  Num_Credit_Card           10000 non-null  float64
 14  Interest_Rate             10000 non-null  float64
 15  Num_of_Loan               10000 non-null  float64
 16  Monthly_Inhand_Salary     10000 non-null  float64
 17  Changed_Credit_Limit      10000 non-null  float64
 18  Outstanding_Debt          10000 non-null  float64
 19  Total_EMI_per_month       10000 non-null  float64
dtypes: category(3), float64(17)
memory usage: 1.3 MB

In [18]:
train

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Score,Credit_Mix,...,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
0,56.0,16.0,11.0,35.598217,120.0,2,229.093478,252.385965,1,0,...,15.0,36597.56,8.0,10.0,29.0,5.0,3143.796667,22.49,2963.18,122.900223
1,49.0,23.0,12.0,25.553106,120.0,2,104.613906,219.105944,1,0,...,28.0,32057.30,9.0,8.0,16.0,7.0,2606.441667,1.40,1327.26,164.859426
2,34.0,20.0,6.0,40.039954,174.0,2,338.626965,251.265589,1,0,...,46.0,75868.80,6.0,10.0,32.0,7.0,6074.400000,3.60,1432.71,297.547446
3,21.0,13.0,8.0,25.711678,143.0,0,116.816864,259.927960,2,2,...,46.0,17092.69,7.0,3.0,19.0,7.0,1695.390833,16.40,1417.06,62.794260
4,19.0,13.0,6.0,39.140463,138.0,2,87.262887,626.212330,1,0,...,45.0,81471.96,6.0,6.0,25.0,5.0,6763.330000,27.09,2679.69,202.857783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,13.0,20.0,1.0,28.311154,358.0,1,160.363681,317.931124,2,2,...,25.0,36661.93,6.0,3.0,10.0,4.0,2915.160833,1.16,314.26,73.221279
9996,32.0,13.0,5.0,39.741948,299.0,2,278.359264,160.416098,2,2,...,48.0,28161.85,8.0,5.0,6.0,4.0,2422.820833,7.72,699.69,93.506721
9997,13.0,9.0,8.0,25.111049,203.0,2,39.334921,352.515899,2,2,...,36.0,39912.86,3.0,4.0,17.0,6.0,3498.071667,15.72,1734.43,197.956347
9998,10.0,13.0,6.0,32.237478,309.0,2,115.463482,354.829742,2,2,...,45.0,26918.38,6.0,5.0,10.0,2.0,2442.198333,5.48,1054.90,43.926610
9999,14.0,12.0,2.0,32.525388,288.0,0,655.490743,636.379413,3,1,...,50.0,148786.04,4.0,4.0,4.0,3.0,12492.836667,6.71,399.45,237.413511

In [19]:
test

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Mix,Payment_Behaviour,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
0,4.0,8.0,2.0,33.444469,239.0,1,104.467859,503.976904,1,5,54.0,43754.320,5.0,7.0,7.0,1.0,3938.193333,7.55,515.73,35.374569
1,31.0,19.0,14.0,27.762143,93.0,2,149.137974,219.372773,0,2,40.0,18836.230,6.0,8.0,16.0,6.0,1280.685833,14.26,1310.56,49.557837
2,55.0,16.0,17.0,38.985106,179.0,2,21.862086,299.525207,2,5,27.0,9360.515,8.0,6.0,15.0,5.0,531.042917,11.92,2113.29,21.716999
3,47.0,20.0,8.0,25.577407,93.0,2,170.009215,161.283266,0,5,34.0,30386.200,7.0,8.0,21.0,9.0,2650.183333,17.53,4902.83,193.725852
4,26.0,11.0,7.0,36.580166,207.0,2,296.552469,177.231449,2,1,36.0,49187.070,6.0,6.0,25.0,6.0,3823.922500,12.04,1357.26,198.608332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,27.0,12.0,4.0,38.977305,383.0,2,39.695906,472.869011,2,1,32.0,38839.220,8.0,4.0,19.0,3.0,3272.601667,1.83,1203.51,64.695250
9996,22.0,19.0,2.0,25.582411,363.0,2,89.540202,360.819998,2,1,51.0,24251.490,8.0,4.0,14.0,1.0,1991.957500,10.53,1062.17,18.835550
9997,20.0,15.0,11.0,26.764418,233.0,2,53.574209,311.419464,0,5,45.0,15806.840,6.0,5.0,21.0,3.0,1140.236667,3.41,2580.63,29.029993
9998,60.0,19.0,8.0,35.262194,99.0,0,46.902804,389.691164,0,2,40.0,35462.520,8.0,9.0,31.0,4.0,2718.210000,13.14,2371.87,75.227032
9999,56.0,20.0,7.0,28.104679,139.0,2,31.318074,284.545251,0,5,26.0,10222.150,6.0,5.0,18.0,9.0,899.845833,27.34,4473.83,54.121258

# 검증 데이터 분할

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(train, y_train, test_size=0.2, random_state=0)

In [10]:
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((8000, 20), (2000, 20), (8000,), (2000,))

# 머신러닝 학습 및 평가

In [25]:
# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0) # 난수값 고정 in -> out 고정값
rf.fit(X_train, y_train) # 모델 학습

RandomForestClassifier(random_state=0)

In [28]:
pred_rf = rf.predict_proba(X_val)
pred_rf

array([[0.43, 0.55, 0.02],
       [0.09, 0.88, 0.03],
       [0.06, 0.78, 0.16],
       ...,
       [0.04, 0.29, 0.67],
       [0.02, 0.95, 0.03],
       [0.16, 0.39, 0.45]])

In [11]:
# LIGHTGBM 학습
import lightgbm as lgb
lgbmc = lgb.LGBMClassifier(random_state=0, verbose=1)
lgbmc.fit(X_train, y_train)
pred = lgbmc.predict(X_val) # 예측 y값
pred
pred_proba = lgbmc.predict_proba(X_val) # 예측 확률값

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000967 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2529
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 20
[LightGBM] [Info] Start training from score -1.208148
[LightGBM] [Info] Start training from score -0.643881
[LightGBM] [Info] Start training from score -1.737271

# 평가

In [13]:
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

# roc_auc_score(실제_레이블, 예측_확률_또는_점수)
# ovr(One-vs-Rest) : 각 클래스 vs 나머지 -> 평균
# ovo(One-vs-One) : 클래스 쌍별 AUC 평균

roc_auc_ovr = roc_auc_score(y_val, pred_proba, multi_class="ovr") # 예측 확률값 [오답예측확률, 정답예측확률] 
roc_auc_ovo = roc_auc_score(y_val, pred_proba, multi_class="ovo")

accuracy = accuracy_score(y_val, pred) # pred 예측 y값
f1 = f1_score(y_val, pred, average='macro') # pred 예측 y값(클래스별 (1, 2, 3 정답값) 성능을 동등하게 반영)

print('roc_auc_ovr : ', roc_auc_ovr)
print('roc_auc_ovo : ', roc_auc_ovo)
print('accuracy : ', accuracy)
print('f1 : ', f1)

roc_auc_ovr :  0.8507625027884959
roc_auc_ovo :  0.8575703288828868
accuracy :  0.6985
f1 :  0.6777379561595467

# 파일 제출

In [34]:
pred_submit = lgbmc.predict(test)
pred_submit

array([3, 1, 1, ..., 1, 1, 2])

In [35]:
submit_csv = pd.DataFrame({'pred':pred_submit})
submit_csv.to_csv("result.csv", index=False)